// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awscontroltower;

import com.pulumi.awscontroltower.inputs.ProviderAssumeRoleArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * This is the AWS access key. It must be provided, but it can also be sourced from the `AWS_ACCESS_KEY_ID` environment
     * variable, or via a shared credentials file if `profile` is specified.
     * 
     */
    @Import(name="accessKey")
    private @Nullable Output<String> accessKey;

    /**
     * @return This is the AWS access key. It must be provided, but it can also be sourced from the `AWS_ACCESS_KEY_ID` environment
     * variable, or via a shared credentials file if `profile` is specified.
     * 
     */
    public Optional<Output<String>> accessKey() {
        return Optional.ofNullable(this.accessKey);
    }

    /**
     * Settings for making use of the AWS Assume Role functionality.
     * 
     */
    @Import(name="assumeRole", json=true)
    private @Nullable Output<ProviderAssumeRoleArgs> assumeRole;

    /**
     * @return Settings for making use of the AWS Assume Role functionality.
     * 
     */
    public Optional<Output<ProviderAssumeRoleArgs>> assumeRole() {
        return Optional.ofNullable(this.assumeRole);
    }

    /**
     * This is the maximum number of times an API call is retried, in the case where requests are being throttled or
     * experiencing transient failures. The delay between the subsequent API calls increases exponentially. If omitted, the
     * default value is `25`.
     * 
     */
    @Import(name="maxRetries", json=true)
    private @Nullable Output<Integer> maxRetries;

    /**
     * @return This is the maximum number of times an API call is retried, in the case where requests are being throttled or
     * experiencing transient failures. The delay between the subsequent API calls increases exponentially. If omitted, the
     * default value is `25`.
     * 
     */
    public Optional<Output<Integer>> maxRetries() {
        return Optional.ofNullable(this.maxRetries);
    }

    /**
     * This is the AWS profile name as set in the shared credentials file.
     * 
     */
    @Import(name="profile")
    private @Nullable Output<String> profile;

    /**
     * @return This is the AWS profile name as set in the shared credentials file.
     * 
     */
    public Optional<Output<String>> profile() {
        return Optional.ofNullable(this.profile);
    }

    /**
     * This is the AWS region. It must be provided, but it can also be sourced from the `AWS_DEFAULT_REGION` environment
     * variables, or via a shared credentials file if `profile` is specified.
     * 
     */
    @Import(name="region", required=true)
    private Output<String> region;

    /**
     * @return This is the AWS region. It must be provided, but it can also be sourced from the `AWS_DEFAULT_REGION` environment
     * variables, or via a shared credentials file if `profile` is specified.
     * 
     */
    public Output<String> region() {
        return this.region;
    }

    /**
     * This is the AWS secret key. It must be provided, but it can also be sourced from the `AWS_SECRET_ACCESS_KEY` environment
     * variable, or via a shared credentials file if `profile` is specified.
     * 
     */
    @Import(name="secretKey")
    private @Nullable Output<String> secretKey;

    /**
     * @return This is the AWS secret key. It must be provided, but it can also be sourced from the `AWS_SECRET_ACCESS_KEY` environment
     * variable, or via a shared credentials file if `profile` is specified.
     * 
     */
    public Optional<Output<String>> secretKey() {
        return Optional.ofNullable(this.secretKey);
    }

    /**
     * This is the path to the shared credentials file. If this is not set and a profile is specified, `~/.aws/credentials`
     * will be used.
     * 
     */
    @Import(name="sharedCredentialsFile")
    private @Nullable Output<String> sharedCredentialsFile;

    /**
     * @return This is the path to the shared credentials file. If this is not set and a profile is specified, `~/.aws/credentials`
     * will be used.
     * 
     */
    public Optional<Output<String>> sharedCredentialsFile() {
        return Optional.ofNullable(this.sharedCredentialsFile);
    }

    /**
     * Skip the credentials validation via the STS API. Useful for AWS API implementations that do not have STS available or
     * implemented.
     * 
     */
    @Import(name="skipCredentialsValidation", json=true)
    private @Nullable Output<Boolean> skipCredentialsValidation;

    /**
     * @return Skip the credentials validation via the STS API. Useful for AWS API implementations that do not have STS available or
     * implemented.
     * 
     */
    public Optional<Output<Boolean>> skipCredentialsValidation() {
        return Optional.ofNullable(this.skipCredentialsValidation);
    }

    /**
     * Skip the AWS Metadata API check. Useful for AWS API implementations that do not have a metadata API endpoint. Setting to
     * `true` prevents Terraform from authenticating via the Metadata API. You may need to use other authentication methods
     * like static credentials, configuration variables, or environment variables.
     * 
     */
    @Import(name="skipMetadataApiCheck", json=true)
    private @Nullable Output<Boolean> skipMetadataApiCheck;

    /**
     * @return Skip the AWS Metadata API check. Useful for AWS API implementations that do not have a metadata API endpoint. Setting to
     * `true` prevents Terraform from authenticating via the Metadata API. You may need to use other authentication methods
     * like static credentials, configuration variables, or environment variables.
     * 
     */
    public Optional<Output<Boolean>> skipMetadataApiCheck() {
        return Optional.ofNullable(this.skipMetadataApiCheck);
    }

    /**
     * Skip requesting the account ID. Useful for AWS API implementations that do not have the IAM, STS API, or metadata API.
     * 
     */
    @Import(name="skipRequestingAccountId", json=true)
    private @Nullable Output<Boolean> skipRequestingAccountId;

    /**
     * @return Skip requesting the account ID. Useful for AWS API implementations that do not have the IAM, STS API, or metadata API.
     * 
     */
    public Optional<Output<Boolean>> skipRequestingAccountId() {
        return Optional.ofNullable(this.skipRequestingAccountId);
    }

    /**
     * Session token for validating temporary credentials. Typically provided after successful identity federation or
     * Multi-Factor Authentication (MFA) login. With MFA login, this is the session token provided afterward, not the 6 digit
     * MFA code used to get temporary credentials. It can also be sourced from the `AWS_SESSION_TOKEN` environment variable.
     * 
     */
    @Import(name="token")
    private @Nullable Output<String> token;

    /**
     * @return Session token for validating temporary credentials. Typically provided after successful identity federation or
     * Multi-Factor Authentication (MFA) login. With MFA login, this is the session token provided afterward, not the 6 digit
     * MFA code used to get temporary credentials. It can also be sourced from the `AWS_SESSION_TOKEN` environment variable.
     * 
     */
    public Optional<Output<String>> token() {
        return Optional.ofNullable(this.token);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.accessKey = $.accessKey;
        this.assumeRole = $.assumeRole;
        this.maxRetries = $.maxRetries;
        this.profile = $.profile;
        this.region = $.region;
        this.secretKey = $.secretKey;
        this.sharedCredentialsFile = $.sharedCredentialsFile;
        this.skipCredentialsValidation = $.skipCredentialsValidation;
        this.skipMetadataApiCheck = $.skipMetadataApiCheck;
        this.skipRequestingAccountId = $.skipRequestingAccountId;
        this.token = $.token;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param accessKey This is the AWS access key. It must be provided, but it can also be sourced from the `AWS_ACCESS_KEY_ID` environment
         * variable, or via a shared credentials file if `profile` is specified.
         * 
         * @return builder
         * 
         */
        public Builder accessKey(@Nullable Output<String> accessKey) {
            $.accessKey = accessKey;
            return this;
        }

        /**
         * @param accessKey This is the AWS access key. It must be provided, but it can also be sourced from the `AWS_ACCESS_KEY_ID` environment
         * variable, or via a shared credentials file if `profile` is specified.
         * 
         * @return builder
         * 
         */
        public Builder accessKey(String accessKey) {
            return accessKey(Output.of(accessKey));
        }

        /**
         * @param assumeRole Settings for making use of the AWS Assume Role functionality.
         * 
         * @return builder
         * 
         */
        public Builder assumeRole(@Nullable Output<ProviderAssumeRoleArgs> assumeRole) {
            $.assumeRole = assumeRole;
            return this;
        }

        /**
         * @param assumeRole Settings for making use of the AWS Assume Role functionality.
         * 
         * @return builder
         * 
         */
        public Builder assumeRole(ProviderAssumeRoleArgs assumeRole) {
            return assumeRole(Output.of(assumeRole));
        }

        /**
         * @param maxRetries This is the maximum number of times an API call is retried, in the case where requests are being throttled or
         * experiencing transient failures. The delay between the subsequent API calls increases exponentially. If omitted, the
         * default value is `25`.
         * 
         * @return builder
         * 
         */
        public Builder maxRetries(@Nullable Output<Integer> maxRetries) {
            $.maxRetries = maxRetries;
            return this;
        }

        /**
         * @param maxRetries This is the maximum number of times an API call is retried, in the case where requests are being throttled or
         * experiencing transient failures. The delay between the subsequent API calls increases exponentially. If omitted, the
         * default value is `25`.
         * 
         * @return builder
         * 
         */
        public Builder maxRetries(Integer maxRetries) {
            return maxRetries(Output.of(maxRetries));
        }

        /**
         * @param profile This is the AWS profile name as set in the shared credentials file.
         * 
         * @return builder
         * 
         */
        public Builder profile(@Nullable Output<String> profile) {
            $.profile = profile;
            return this;
        }

        /**
         * @param profile This is the AWS profile name as set in the shared credentials file.
         * 
         * @return builder
         * 
         */
        public Builder profile(String profile) {
            return profile(Output.of(profile));
        }

        /**
         * @param region This is the AWS region. It must be provided, but it can also be sourced from the `AWS_DEFAULT_REGION` environment
         * variables, or via a shared credentials file if `profile` is specified.
         * 
         * @return builder
         * 
         */
        public Builder region(Output<String> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region This is the AWS region. It must be provided, but it can also be sourced from the `AWS_DEFAULT_REGION` environment
         * variables, or via a shared credentials file if `profile` is specified.
         * 
         * @return builder
         * 
         */
        public Builder region(String region) {
            return region(Output.of(region));
        }

        /**
         * @param secretKey This is the AWS secret key. It must be provided, but it can also be sourced from the `AWS_SECRET_ACCESS_KEY` environment
         * variable, or via a shared credentials file if `profile` is specified.
         * 
         * @return builder
         * 
         */
        public Builder secretKey(@Nullable Output<String> secretKey) {
            $.secretKey = secretKey;
            return this;
        }

        /**
         * @param secretKey This is the AWS secret key. It must be provided, but it can also be sourced from the `AWS_SECRET_ACCESS_KEY` environment
         * variable, or via a shared credentials file if `profile` is specified.
         * 
         * @return builder
         * 
         */
        public Builder secretKey(String secretKey) {
            return secretKey(Output.of(secretKey));
        }

        /**
         * @param sharedCredentialsFile This is the path to the shared credentials file. If this is not set and a profile is specified, `~/.aws/credentials`
         * will be used.
         * 
         * @return builder
         * 
         */
        public Builder sharedCredentialsFile(@Nullable Output<String> sharedCredentialsFile) {
            $.sharedCredentialsFile = sharedCredentialsFile;
            return this;
        }

        /**
         * @param sharedCredentialsFile This is the path to the shared credentials file. If this is not set and a profile is specified, `~/.aws/credentials`
         * will be used.
         * 
         * @return builder
         * 
         */
        public Builder sharedCredentialsFile(String sharedCredentialsFile) {
            return sharedCredentialsFile(Output.of(sharedCredentialsFile));
        }

        /**
         * @param skipCredentialsValidation Skip the credentials validation via the STS API. Useful for AWS API implementations that do not have STS available or
         * implemented.
         * 
         * @return builder
         * 
         */
        public Builder skipCredentialsValidation(@Nullable Output<Boolean> skipCredentialsValidation) {
            $.skipCredentialsValidation = skipCredentialsValidation;
            return this;
        }

        /**
         * @param skipCredentialsValidation Skip the credentials validation via the STS API. Useful for AWS API implementations that do not have STS available or
         * implemented.
         * 
         * @return builder
         * 
         */
        public Builder skipCredentialsValidation(Boolean skipCredentialsValidation) {
            return skipCredentialsValidation(Output.of(skipCredentialsValidation));
        }

        /**
         * @param skipMetadataApiCheck Skip the AWS Metadata API check. Useful for AWS API implementations that do not have a metadata API endpoint. Setting to
         * `true` prevents Terraform from authenticating via the Metadata API. You may need to use other authentication methods
         * like static credentials, configuration variables, or environment variables.
         * 
         * @return builder
         * 
         */
        public Builder skipMetadataApiCheck(@Nullable Output<Boolean> skipMetadataApiCheck) {
            $.skipMetadataApiCheck = skipMetadataApiCheck;
            return this;
        }

        /**
         * @param skipMetadataApiCheck Skip the AWS Metadata API check. Useful for AWS API implementations that do not have a metadata API endpoint. Setting to
         * `true` prevents Terraform from authenticating via the Metadata API. You may need to use other authentication methods
         * like static credentials, configuration variables, or environment variables.
         * 
         * @return builder
         * 
         */
        public Builder skipMetadataApiCheck(Boolean skipMetadataApiCheck) {
            return skipMetadataApiCheck(Output.of(skipMetadataApiCheck));
        }

        /**
         * @param skipRequestingAccountId Skip requesting the account ID. Useful for AWS API implementations that do not have the IAM, STS API, or metadata API.
         * 
         * @return builder
         * 
         */
        public Builder skipRequestingAccountId(@Nullable Output<Boolean> skipRequestingAccountId) {
            $.skipRequestingAccountId = skipRequestingAccountId;
            return this;
        }

        /**
         * @param skipRequestingAccountId Skip requesting the account ID. Useful for AWS API implementations that do not have the IAM, STS API, or metadata API.
         * 
         * @return builder
         * 
         */
        public Builder skipRequestingAccountId(Boolean skipRequestingAccountId) {
            return skipRequestingAccountId(Output.of(skipRequestingAccountId));
        }

        /**
         * @param token Session token for validating temporary credentials. Typically provided after successful identity federation or
         * Multi-Factor Authentication (MFA) login. With MFA login, this is the session token provided afterward, not the 6 digit
         * MFA code used to get temporary credentials. It can also be sourced from the `AWS_SESSION_TOKEN` environment variable.
         * 
         * @return builder
         * 
         */
        public Builder token(@Nullable Output<String> token) {
            $.token = token;
            return this;
        }

        /**
         * @param token Session token for validating temporary credentials. Typically provided after successful identity federation or
         * Multi-Factor Authentication (MFA) login. With MFA login, this is the session token provided afterward, not the 6 digit
         * MFA code used to get temporary credentials. It can also be sourced from the `AWS_SESSION_TOKEN` environment variable.
         * 
         * @return builder
         * 
         */
        public Builder token(String token) {
            return token(Output.of(token));
        }

        public ProviderArgs build() {
            $.region = Objects.requireNonNull($.region, "expected parameter 'region' to be non-null");
            return $;
        }
    }

}
