// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Lbrlabs.PulumiPackage.Awscontroltower.Outputs
{

    [OutputType]
    public sealed class ControlTowerAwsAccountSso
    {
        public readonly string Email;
        public readonly string FirstName;
        public readonly string LastName;

        [OutputConstructor]
        private ControlTowerAwsAccountSso(
            string email,

            string firstName,

            string lastName)
        {
            Email = email;
            FirstName = firstName;
            LastName = lastName;
        }
    }
}
