# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from . import outputs

accessKey: Optional[str]
"""
This is the AWS access key. It must be provided, but it can also be sourced from the `AWS_ACCESS_KEY_ID` environment
variable, or via a shared credentials file if `profile` is specified.
"""

assumeRole: Optional[str]
"""
Settings for making use of the AWS Assume Role functionality.
"""

maxRetries: Optional[int]
"""
This is the maximum number of times an API call is retried, in the case where requests are being throttled or
experiencing transient failures. The delay between the subsequent API calls increases exponentially. If omitted, the
default value is `25`.
"""

profile: Optional[str]
"""
This is the AWS profile name as set in the shared credentials file.
"""

region: Optional[str]
"""
This is the AWS region. It must be provided, but it can also be sourced from the `AWS_DEFAULT_REGION` environment
variables, or via a shared credentials file if `profile` is specified.
"""

secretKey: Optional[str]
"""
This is the AWS secret key. It must be provided, but it can also be sourced from the `AWS_SECRET_ACCESS_KEY` environment
variable, or via a shared credentials file if `profile` is specified.
"""

sharedCredentialsFile: Optional[str]
"""
This is the path to the shared credentials file. If this is not set and a profile is specified, `~/.aws/credentials`
will be used.
"""

skipCredentialsValidation: Optional[bool]
"""
Skip the credentials validation via the STS API. Useful for AWS API implementations that do not have STS available or
implemented.
"""

skipMetadataApiCheck: Optional[bool]
"""
Skip the AWS Metadata API check. Useful for AWS API implementations that do not have a metadata API endpoint. Setting to
`true` prevents Terraform from authenticating via the Metadata API. You may need to use other authentication methods
like static credentials, configuration variables, or environment variables.
"""

skipRequestingAccountId: Optional[bool]
"""
Skip requesting the account ID. Useful for AWS API implementations that do not have the IAM, STS API, or metadata API.
"""

token: Optional[str]
"""
Session token for validating temporary credentials. Typically provided after successful identity federation or
Multi-Factor Authentication (MFA) login. With MFA login, this is the session token provided afterward, not the 6 digit
MFA code used to get temporary credentials. It can also be sourced from the `AWS_SESSION_TOKEN` environment variable.
"""

