// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awscontroltower.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class ControlTowerAwsAccountSso {
    private String email;
    private String firstName;
    private String lastName;

    private ControlTowerAwsAccountSso() {}
    public String email() {
        return this.email;
    }
    public String firstName() {
        return this.firstName;
    }
    public String lastName() {
        return this.lastName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ControlTowerAwsAccountSso defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String email;
        private String firstName;
        private String lastName;
        public Builder() {}
        public Builder(ControlTowerAwsAccountSso defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.email = defaults.email;
    	      this.firstName = defaults.firstName;
    	      this.lastName = defaults.lastName;
        }

        @CustomType.Setter
        public Builder email(String email) {
            this.email = Objects.requireNonNull(email);
            return this;
        }
        @CustomType.Setter
        public Builder firstName(String firstName) {
            this.firstName = Objects.requireNonNull(firstName);
            return this;
        }
        @CustomType.Setter
        public Builder lastName(String lastName) {
            this.lastName = Objects.requireNonNull(lastName);
            return this;
        }
        public ControlTowerAwsAccountSso build() {
            final var o = new ControlTowerAwsAccountSso();
            o.email = email;
            o.firstName = firstName;
            o.lastName = lastName;
            return o;
        }
    }
}
