// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package awscontroltower

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the awscontroltower package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// This is the AWS access key. It must be provided, but it can also be sourced from the `AWS_ACCESS_KEY_ID` environment
	// variable, or via a shared credentials file if `profile` is specified.
	AccessKey pulumi.StringPtrOutput `pulumi:"accessKey"`
	// This is the AWS profile name as set in the shared credentials file.
	Profile pulumi.StringPtrOutput `pulumi:"profile"`
	// This is the AWS region. It must be provided, but it can also be sourced from the `AWS_DEFAULT_REGION` environment
	// variables, or via a shared credentials file if `profile` is specified.
	Region pulumi.StringOutput `pulumi:"region"`
	// This is the AWS secret key. It must be provided, but it can also be sourced from the `AWS_SECRET_ACCESS_KEY` environment
	// variable, or via a shared credentials file if `profile` is specified.
	SecretKey pulumi.StringPtrOutput `pulumi:"secretKey"`
	// This is the path to the shared credentials file. If this is not set and a profile is specified, `~/.aws/credentials`
	// will be used.
	SharedCredentialsFile pulumi.StringPtrOutput `pulumi:"sharedCredentialsFile"`
	// Session token for validating temporary credentials. Typically provided after successful identity federation or
	// Multi-Factor Authentication (MFA) login. With MFA login, this is the session token provided afterward, not the 6 digit
	// MFA code used to get temporary credentials. It can also be sourced from the `AWS_SESSION_TOKEN` environment variable.
	Token pulumi.StringPtrOutput `pulumi:"token"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Region == nil {
		return nil, errors.New("invalid value for required argument 'Region'")
	}
	opts = pkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:awscontroltower", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// This is the AWS access key. It must be provided, but it can also be sourced from the `AWS_ACCESS_KEY_ID` environment
	// variable, or via a shared credentials file if `profile` is specified.
	AccessKey *string `pulumi:"accessKey"`
	// Settings for making use of the AWS Assume Role functionality.
	AssumeRole *ProviderAssumeRole `pulumi:"assumeRole"`
	// This is the maximum number of times an API call is retried, in the case where requests are being throttled or
	// experiencing transient failures. The delay between the subsequent API calls increases exponentially. If omitted, the
	// default value is `25`.
	MaxRetries *int `pulumi:"maxRetries"`
	// This is the AWS profile name as set in the shared credentials file.
	Profile *string `pulumi:"profile"`
	// This is the AWS region. It must be provided, but it can also be sourced from the `AWS_DEFAULT_REGION` environment
	// variables, or via a shared credentials file if `profile` is specified.
	Region string `pulumi:"region"`
	// This is the AWS secret key. It must be provided, but it can also be sourced from the `AWS_SECRET_ACCESS_KEY` environment
	// variable, or via a shared credentials file if `profile` is specified.
	SecretKey *string `pulumi:"secretKey"`
	// This is the path to the shared credentials file. If this is not set and a profile is specified, `~/.aws/credentials`
	// will be used.
	SharedCredentialsFile *string `pulumi:"sharedCredentialsFile"`
	// Skip the credentials validation via the STS API. Useful for AWS API implementations that do not have STS available or
	// implemented.
	SkipCredentialsValidation *bool `pulumi:"skipCredentialsValidation"`
	// Skip the AWS Metadata API check. Useful for AWS API implementations that do not have a metadata API endpoint. Setting to
	// `true` prevents Terraform from authenticating via the Metadata API. You may need to use other authentication methods
	// like static credentials, configuration variables, or environment variables.
	SkipMetadataApiCheck *bool `pulumi:"skipMetadataApiCheck"`
	// Skip requesting the account ID. Useful for AWS API implementations that do not have the IAM, STS API, or metadata API.
	SkipRequestingAccountId *bool `pulumi:"skipRequestingAccountId"`
	// Session token for validating temporary credentials. Typically provided after successful identity federation or
	// Multi-Factor Authentication (MFA) login. With MFA login, this is the session token provided afterward, not the 6 digit
	// MFA code used to get temporary credentials. It can also be sourced from the `AWS_SESSION_TOKEN` environment variable.
	Token *string `pulumi:"token"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// This is the AWS access key. It must be provided, but it can also be sourced from the `AWS_ACCESS_KEY_ID` environment
	// variable, or via a shared credentials file if `profile` is specified.
	AccessKey pulumi.StringPtrInput
	// Settings for making use of the AWS Assume Role functionality.
	AssumeRole ProviderAssumeRolePtrInput
	// This is the maximum number of times an API call is retried, in the case where requests are being throttled or
	// experiencing transient failures. The delay between the subsequent API calls increases exponentially. If omitted, the
	// default value is `25`.
	MaxRetries pulumi.IntPtrInput
	// This is the AWS profile name as set in the shared credentials file.
	Profile pulumi.StringPtrInput
	// This is the AWS region. It must be provided, but it can also be sourced from the `AWS_DEFAULT_REGION` environment
	// variables, or via a shared credentials file if `profile` is specified.
	Region pulumi.StringInput
	// This is the AWS secret key. It must be provided, but it can also be sourced from the `AWS_SECRET_ACCESS_KEY` environment
	// variable, or via a shared credentials file if `profile` is specified.
	SecretKey pulumi.StringPtrInput
	// This is the path to the shared credentials file. If this is not set and a profile is specified, `~/.aws/credentials`
	// will be used.
	SharedCredentialsFile pulumi.StringPtrInput
	// Skip the credentials validation via the STS API. Useful for AWS API implementations that do not have STS available or
	// implemented.
	SkipCredentialsValidation pulumi.BoolPtrInput
	// Skip the AWS Metadata API check. Useful for AWS API implementations that do not have a metadata API endpoint. Setting to
	// `true` prevents Terraform from authenticating via the Metadata API. You may need to use other authentication methods
	// like static credentials, configuration variables, or environment variables.
	SkipMetadataApiCheck pulumi.BoolPtrInput
	// Skip requesting the account ID. Useful for AWS API implementations that do not have the IAM, STS API, or metadata API.
	SkipRequestingAccountId pulumi.BoolPtrInput
	// Session token for validating temporary credentials. Typically provided after successful identity federation or
	// Multi-Factor Authentication (MFA) login. With MFA login, this is the session token provided afterward, not the 6 digit
	// MFA code used to get temporary credentials. It can also be sourced from the `AWS_SESSION_TOKEN` environment variable.
	Token pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// This is the AWS access key. It must be provided, but it can also be sourced from the `AWS_ACCESS_KEY_ID` environment
// variable, or via a shared credentials file if `profile` is specified.
func (o ProviderOutput) AccessKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.AccessKey }).(pulumi.StringPtrOutput)
}

// This is the AWS profile name as set in the shared credentials file.
func (o ProviderOutput) Profile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Profile }).(pulumi.StringPtrOutput)
}

// This is the AWS region. It must be provided, but it can also be sourced from the `AWS_DEFAULT_REGION` environment
// variables, or via a shared credentials file if `profile` is specified.
func (o ProviderOutput) Region() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.Region }).(pulumi.StringOutput)
}

// This is the AWS secret key. It must be provided, but it can also be sourced from the `AWS_SECRET_ACCESS_KEY` environment
// variable, or via a shared credentials file if `profile` is specified.
func (o ProviderOutput) SecretKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.SecretKey }).(pulumi.StringPtrOutput)
}

// This is the path to the shared credentials file. If this is not set and a profile is specified, `~/.aws/credentials`
// will be used.
func (o ProviderOutput) SharedCredentialsFile() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.SharedCredentialsFile }).(pulumi.StringPtrOutput)
}

// Session token for validating temporary credentials. Typically provided after successful identity federation or
// Multi-Factor Authentication (MFA) login. With MFA login, this is the session token provided afterward, not the 6 digit
// MFA code used to get temporary credentials. It can also be sourced from the `AWS_SESSION_TOKEN` environment variable.
func (o ProviderOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Token }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
