// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.awscontroltower.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;


public final class ControlTowerAwsAccountSsoArgs extends com.pulumi.resources.ResourceArgs {

    public static final ControlTowerAwsAccountSsoArgs Empty = new ControlTowerAwsAccountSsoArgs();

    @Import(name="email", required=true)
    private Output<String> email;

    public Output<String> email() {
        return this.email;
    }

    @Import(name="firstName", required=true)
    private Output<String> firstName;

    public Output<String> firstName() {
        return this.firstName;
    }

    @Import(name="lastName", required=true)
    private Output<String> lastName;

    public Output<String> lastName() {
        return this.lastName;
    }

    private ControlTowerAwsAccountSsoArgs() {}

    private ControlTowerAwsAccountSsoArgs(ControlTowerAwsAccountSsoArgs $) {
        this.email = $.email;
        this.firstName = $.firstName;
        this.lastName = $.lastName;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ControlTowerAwsAccountSsoArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ControlTowerAwsAccountSsoArgs $;

        public Builder() {
            $ = new ControlTowerAwsAccountSsoArgs();
        }

        public Builder(ControlTowerAwsAccountSsoArgs defaults) {
            $ = new ControlTowerAwsAccountSsoArgs(Objects.requireNonNull(defaults));
        }

        public Builder email(Output<String> email) {
            $.email = email;
            return this;
        }

        public Builder email(String email) {
            return email(Output.of(email));
        }

        public Builder firstName(Output<String> firstName) {
            $.firstName = firstName;
            return this;
        }

        public Builder firstName(String firstName) {
            return firstName(Output.of(firstName));
        }

        public Builder lastName(Output<String> lastName) {
            $.lastName = lastName;
            return this;
        }

        public Builder lastName(String lastName) {
            return lastName(Output.of(lastName));
        }

        public ControlTowerAwsAccountSsoArgs build() {
            $.email = Objects.requireNonNull($.email, "expected parameter 'email' to be non-null");
            $.firstName = Objects.requireNonNull($.firstName, "expected parameter 'firstName' to be non-null");
            $.lastName = Objects.requireNonNull($.lastName, "expected parameter 'lastName' to be non-null");
            return $;
        }
    }

}
