// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface ControlTowerAwsAccountSso {
    email: string;
    firstName: string;
    lastName: string;
}

export namespace config {
    export interface AssumeRole {
        durationSeconds?: number;
        externalId?: string;
        policy?: string;
        policyArns?: string[];
        roleArn?: string;
        sessionName?: string;
        tags?: {[key: string]: string};
        transitiveTagKeys?: string[];
    }

}
